eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:19102/eureka/
---
spring:
    profiles: docker
eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery-server:19102/eureka/
