server:
    port: 19111


spring:
    datasource:
        initialization-mode: always
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/medipractice
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
                format_sql: true
    redis:
        host: localhost
        port: 6379


security:
    oauth2:
        resource:
            filter-order: 3

medipractice:
    client:
        id: 'medipractice'
        secret: 'medipractice'
