server:
    port: 9092

spring:
    datasource:
        initialization-mode: always
        url: jdbc:postgresql://localhost:5432/medipractice
        username: postgres
        password: 123456
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true


security:
    oauth2:
        resource:
            id: datafile-service
            user-info-uri: http://localhost:9090/user
            prefer-token-info: false
