server:
    port: 9091

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/medipractice
        username: postgres
        password: 123456
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
