server:
    port: 19113

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/medipractice
        username: postgres
        password: 123456
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true

security:
    oauth2:
        resource:
            id: page-service
            user-info-uri: http://localhost:9090/auth/user
            prefer-token-info: false
