eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9102/eureka/
server:
    port: 9091
spring:
    datasource:
        initialization-mode: always
        password: 123456
        url: jdbc:postgresql://localhost:5432/medipractice
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
