server:
    port: 9101
spring:
    application:
        name: ${project.name}
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/SERRAFrank/medipractice-repo.git
