server:
    port: 9101
spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: classpath:shared/
#                git:
#                    uri: https://github.com/SERRAFrank/medipractice-repo.git
endpoints:
    restart:
        enabled: true