server:
    port: 9101
spring:
    application:
        name: config-server
    cloud:
        config:
            label: dev
            server:
                git:
                    uri: https://github.com/SERRAFrank/medipractice-repo.git
